config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/contact'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TailsOnRails6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-800 text-gray-300" >
    <%= yield %>
  </body>
</html>

app/views/partials/icon/_main_logo.html.erb
<svg 
  class="h-6 w-6 text-red-600"
  xmlns="http://www.w3.org/2000/svg" 
  fill="none" 
  viewBox="0 0 24 24" 
  stroke="currentColor">
  <path 
    stroke-linecap="round" 
    stroke-linejoin="round" 
    stroke-width="2" 
    d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
</svg>

app/views/partials/navigation/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<% if activeLink == '1' %>
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2">
    <div class="relative flex items-center justify-between h-16">
      <h1 class="text-gray-300 text-2xl">Associa<span class="text-red-600 font-bold">Plus</span></h1>
      <%= render(partial:'partials/icon/main_logo')%>
      <div class="flex-1 flex items-center justify-end">
        <div class="flex space-x-4">
          <%= link_to "Accueil", welcome_index_path, class: "bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to "Contact", welcome_contact_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <%= link_to "Connexion", welcome_index_path, class: "text-red-500 hover:bg-gray-700 hover:text-red:600 px-3 py-2 rounded-md text-sm font-bold" %>
        </div>
      </div>
    </div>
  </div>
</nav>
<% else activeLink == '2' %>
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2">
    <div class="relative flex items-center justify-between h-16">
      <h1 class="text-gray-300 text-2xl">Associa<span class="text-red-600 font-bold">Plus</span></h1>
      <%= render(partial:'partials/icon/main_logo')%>
      <div class="flex-1 flex items-center justify-end">
        <div class="flex space-x-4">
            <%= link_to "Accueil", welcome_index_path, class: "text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Contact", welcome_contact_path, class: "bg-gray-900 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Connexion", welcome_index_path, class: "text-red-500 hover:bg-gray-700 hover:text-red:600 px-3 py-2 rounded-md text-sm font-bold" %>
        </div>
      </div>
    </div>
  </div>
</nav>
<% end %>

app/views/welcome/contact.html.erb
<%= render(partial:'partials/navigation/navbar', locals: {
    activeLink: '2'
}) %>
<div class="container mx-auto my-5">
</div>

app/views/welcome/index.html.erb
<%= render(partial:'partials/navigation/navbar', locals: {
    activeLink: '1'
}) %>
<div class="container mx-auto mt-20">
    <div class="flex flex-row">

        <div class="flex flex-col">
            <div>
                <h1 class="text-6xl font-bold">Logiciel de gestion pour <span class="text-red-600">association suisses</span></h1>
                <h3 class="text-l text-gray-400 mt-2">AssociaPlus est une solution en ligne pour gérer la comptabilité, les membres et les activités de votre association.</h3>
            </div>
            <div class="mt-20">
                <button class=" text-xl p-4 font-semibold rounded-lg shadow-md bg-green-500 hover:bg-green-700 w-3/4">Créez votre compte gratuitement !</button>
            </div>
        </div>

        <div>
            <%= render 'partials/icon/main_image' %>
        </div>

    </div>

    <div class="py-12 mt-20 ">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="lg:text-center">
        <h2 class="text-base text-red-600 font-semibold tracking-wide uppercase">Fonctionnalités</h2>
        <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight sm:text-4xl">
            Une façon plus simple de gérer votre association.
        </p>
        <p class="mt-4 w-3/4 text-l text-gray-400 lg:mx-auto">
            AssociaPlus vous aide au quotidien dans la maitrise de votre association en vous fournissant des outils de contrôles des membres ou gestion de comptabilité.
        </p>
        </div>

        <div class="mt-10">
        <dl class="space-y-10 md:space-y-0 md:grid md:grid-cols-3 md:gap-x-8 md:gap-y-10">
            <%= render 'welcome/partials/feature_card'%>
            <%= render 'welcome/partials/feature_card' %>
            <%= render 'welcome/partials/feature_card' %>
        </dl>
        </div>
    </div>
    </div>
    
</div>

app/views/welcome/partials/_feature_card.html.erb
<div class="flex p-3 rounded-lg bg-gray-300 hover:shadow-lg hover:bg-gray-400">
    <div class="flex-shrink-0">
    <div class="flex items-center justify-center h-12 w-12 rounded-md bg-red-500 text-white">
        <!-- Heroicon name: globe-alt -->
        <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" />
        </svg>
    </div>
    </div>
    <div class="ml-4">
    <dt class="text-lg leading-6 font-medium text-gray-900">
        Organisation
    </dt>
    <dd class="mt-2 text-base text-gray-700">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores impedit perferendis suscipit eaque, iste dolor cupiditate blanditiis ratione.
    </dd>
    </div>
</div>